name: webapi
services:
  redis:
    image: redis
    ports:
    - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.3.0 # Kafka broker docker image. #specific this version otherwise it required KRaft
    container_name: kafka # Friendly container name.
    ports:
      - 9092:9092  # Exposes Kafka broker port from container to host machine.
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 # Address of ZooKeeper instance used by Kafka.
      - KAFKA_BROKER_ID=1 # # Unique identifier for this Kafka broker. Required in multi broker cluster
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 # # Address Kafka tells clients to use after initial connection.
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092 # Actual network interface Kafka listens on inside container.
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT  # Maps listener name to security protocol.
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT # Listener brokers use internally to communicate with each other.
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true # Automatically creates topic if producer sends to non-existing topic.
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 # Replication factor for Kafka internal offsets topic:
    networks:
      - kafka
networks:
  kafka: 