Create TABLE dbo.products (
	id INT PRIMARY KEY NOT NULL,
	guid UNIQUEIDENTIFIER NOT NULL,
	name NVARCHAR(MAX) NOT NULL,
	sku NVARCHAR(50) NOT NULL,
	currency NVARCHAR(5) NOT NULL,
	amount DECIMAL NOT NULL
)