CREATE TABLE dbo.Users (
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	guid UNIQUEIDENTIFIER NOT NULL,
	first_name NVARCHAR(100) NOT NULL,
	last_name NVARCHAR(100) NOT NULL,
	date_of_birth DATE NOT NULL,
	email NVARCHAR(255) NOT NULL UNIQUE,
	username NVARCHAR(30) NOT NULL UNIQUE,
	password NVARCHAR(255) NOT NULL,
	role INT NOT NULL,
)